stages:
  - test
  - compile
  - build
  - push

test:
  stage: test
  image: trion/ng-cli-karma:12.0.4
  script:
    - npm ci
    - npm test

compile:
  stage: compile
  image: trion/ng-cli-karma:12.0.4
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  script:
    - npm ci
    - npm run build-prod

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /root/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor --cleanup --snapshotMode=redo --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  dependencies:
    - compile

push_latest:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: { }
  variables:
    GIT_STRATEGY: none
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

push_tags:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: { }
  variables:
    GIT_STRATEGY: none
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_COMMIT_TAG
  only:
    - tags
  except:
    - branches

after_script:
  - echo "End CI"
